// <auto-generated />
namespace odk.Scheduler.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AddResource : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddResource));
        
        string IMigrationMetadata.Id
        {
            get { return "202003061036369_AddResourc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
