//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odk.Scheduler.BluePrism.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RPA_BluePrismEntities : DbContext
    {
        public RPA_BluePrismEntities()
            : base("name=RPA_BluePrismEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BPAProcess> BPAProcess { get; set; }
        public virtual DbSet<BPAResource> BPAResource { get; set; }
        public virtual DbSet<BPASession> BPASession { get; set; }
        public virtual DbSet<BPVSession> BPVSession { get; set; }
        public virtual DbSet<BPVSessionInfo> BPVSessionInfo { get; set; }
        public virtual DbSet<BPVWorkQueueItem> BPVWorkQueueItem { get; set; }
    }
}
