//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odk.Scheduler.BluePrism.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPAProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BPAProcess()
        {
            this.BPASession = new HashSet<BPASession>();
        }
    
        public System.Guid processid { get; set; }
        public string ProcessType { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string version { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.Guid> createdby { get; set; }
        public Nullable<System.DateTime> lastmodifieddate { get; set; }
        public Nullable<System.Guid> lastmodifiedby { get; set; }
        public int AttributeID { get; set; }
        public byte[] compressedxml { get; set; }
        public string processxml { get; set; }
        public string wspublishname { get; set; }
        public int runmode { get; set; }
        public bool sharedObject { get; set; }
        public bool forceLiteralForm { get; set; }
        public bool useLegacyNamespace { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BPASession> BPASession { get; set; }
    }
}
