//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odk.Scheduler.BluePrism.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPAResource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BPAResource()
        {
            this.startingresource = new HashSet<BPASession>();
            this.runningresource = new HashSet<BPASession>();
        }
    
        public System.Guid resourceid { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public Nullable<int> processesrunning { get; set; }
        public Nullable<int> actionsrunning { get; set; }
        public Nullable<int> unitsallocated { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public int AttributeID { get; set; }
        public Nullable<System.Guid> pool { get; set; }
        public Nullable<System.Guid> controller { get; set; }
        public int diagnostics { get; set; }
        public bool logtoeventlog { get; set; }
        public string FQDN { get; set; }
        public bool ssl { get; set; }
        public Nullable<System.Guid> userID { get; set; }
        public string DisplayStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BPASession> startingresource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BPASession> runningresource { get; set; }
    }
}
