//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odk.Scheduler.BluePrism.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPVSession
    {
        public System.Guid sessionid { get; set; }
        public int sessionnumber { get; set; }
        public Nullable<System.DateTime> startdatetime { get; set; }
        public Nullable<System.DateTime> enddatetime { get; set; }
        public Nullable<System.Guid> processid { get; set; }
        public Nullable<System.Guid> starterresourceid { get; set; }
        public Nullable<System.Guid> starteruserid { get; set; }
        public Nullable<System.Guid> runningresourceid { get; set; }
        public string runningosusername { get; set; }
        public Nullable<int> statusid { get; set; }
        public string startparamsxml { get; set; }
        public string logginglevelsxml { get; set; }
        public string sessionstatexml { get; set; }
        public Nullable<int> queueid { get; set; }
        public Nullable<System.DateTime> stoprequested { get; set; }
        public Nullable<System.DateTime> stoprequestack { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public string laststage { get; set; }
        public Nullable<int> warningthreshold { get; set; }
        public Nullable<int> starttimezoneoffset { get; set; }
        public Nullable<int> endtimezoneoffset { get; set; }
        public Nullable<int> lastupdatedtimezoneoffset { get; set; }
    }
}
