//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odk.Scheduler.BluePrism.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPVWorkQueueItem
    {
        public long ident { get; set; }
        public System.Guid id { get; set; }
        public System.Guid queueid { get; set; }
        public string keyvalue { get; set; }
        public string status { get; set; }
        public Nullable<int> attempt { get; set; }
        public Nullable<System.DateTime> loaded { get; set; }
        public Nullable<System.DateTime> locked { get; set; }
        public Nullable<System.DateTime> completed { get; set; }
        public Nullable<System.DateTime> exception { get; set; }
        public string exceptionreason { get; set; }
        public Nullable<System.DateTime> deferred { get; set; }
        public Nullable<int> worktime { get; set; }
        public string data { get; set; }
        public int queueident { get; set; }
        public Nullable<System.Guid> sessionid { get; set; }
        public int priority { get; set; }
        public Nullable<System.DateTime> queuepositiondate { get; set; }
        public int prevworktime { get; set; }
        public Nullable<int> attemptworktime { get; set; }
        public Nullable<System.DateTime> finished { get; set; }
        public int state { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public string exceptionreasonvarchar { get; set; }
        public string exceptionreasontag { get; set; }
        public Nullable<int> encryptid { get; set; }
    }
}
